/*
 * generated by Xtext
 */
package de.htwg.msi.dialogicallogic.dsl.ui.contentassist

import de.htwg.msi.dialogicallogic.dsl.ui.contentassist.AbstractLogicProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LogicProposalProvider extends AbstractLogicProposalProvider {
}
