/*
 * generated by Xtext
 */
package de.htwg.msi.dialogicallogic.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LogicRuntimeModule extends de.htwg.msi.dialogicallogic.dsl.AbstractLogicRuntimeModule {

}
