/*
 * generated by Xtext
 */
package de.htwg.msi.dialogicallogic.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LogicStandaloneSetup extends LogicStandaloneSetupGenerated{

	public static void doSetup() {
		new LogicStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

