/*
 * generated by Xtext
 */
package de.htwg.msi.dialogicallogic.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LogicUiModule extends de.htwg.msi.dialogicallogic.dsl.ui.AbstractLogicUiModule {
	public LogicUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
